// automatically generated by the FlatBuffers compiler, do not modify

namespace Core
{

    using System;
    using FlatBuffers;

    public sealed class PhotoFingerPrint : Table
    {
        public static PhotoFingerPrint GetRootAsPhotoFingerPrint(ByteBuffer _bb) { return GetRootAsPhotoFingerPrint(_bb, new PhotoFingerPrint()); }
        public static PhotoFingerPrint GetRootAsPhotoFingerPrint(ByteBuffer _bb, PhotoFingerPrint obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public PhotoFingerPrint __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

        public string FilePath { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
        public ArraySegment<byte>? GetFilePathBytes() { return __vector_as_arraysegment(4); }
        public ulong Phash { get { int o = __offset(6); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }

        public static Offset<PhotoFingerPrint> CreatePhotoFingerPrint(FlatBufferBuilder builder,
            StringOffset filePathOffset = default(StringOffset),
            ulong phash = 0)
        {
            builder.StartObject(2);
            PhotoFingerPrint.AddPhash(builder, phash);
            PhotoFingerPrint.AddFilePath(builder, filePathOffset);
            return PhotoFingerPrint.EndPhotoFingerPrint(builder);
        }

        public static void StartPhotoFingerPrint(FlatBufferBuilder builder) { builder.StartObject(2); }
        public static void AddFilePath(FlatBufferBuilder builder, StringOffset filePathOffset) { builder.AddOffset(0, filePathOffset.Value, 0); }
        public static void AddPhash(FlatBufferBuilder builder, ulong phash) { builder.AddUlong(1, phash, 0); }
        public static Offset<PhotoFingerPrint> EndPhotoFingerPrint(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<PhotoFingerPrint>(o);
        }
    };


}
