// automatically generated by the FlatBuffers compiler, do not modify

namespace Core
{

    using System;
    using FlatBuffers;

    public sealed class VideoFingerPrint : Table
    {
        public static VideoFingerPrint GetRootAsVideoFingerPrint(ByteBuffer _bb) { return GetRootAsVideoFingerPrint(_bb, new VideoFingerPrint()); }
        public static VideoFingerPrint GetRootAsVideoFingerPrint(ByteBuffer _bb, VideoFingerPrint obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public VideoFingerPrint __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

        public string FilePath { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
        public ArraySegment<byte>? GetFilePathBytes() { return __vector_as_arraysegment(4); }
        public FrameFingerPrint GetFrameFingerPrints(int j) { return GetFrameFingerPrints(new FrameFingerPrint(), j); }
        public FrameFingerPrint GetFrameFingerPrints(FrameFingerPrint obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
        public int FrameFingerPrintsLength { get { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; } }

        public static Offset<VideoFingerPrint> CreateVideoFingerPrint(FlatBufferBuilder builder,
            StringOffset filePathOffset = default(StringOffset),
            VectorOffset frameFingerPrintsOffset = default(VectorOffset))
        {
            builder.StartObject(2);
            VideoFingerPrint.AddFrameFingerPrints(builder, frameFingerPrintsOffset);
            VideoFingerPrint.AddFilePath(builder, filePathOffset);
            return VideoFingerPrint.EndVideoFingerPrint(builder);
        }

        public static void StartVideoFingerPrint(FlatBufferBuilder builder) { builder.StartObject(2); }
        public static void AddFilePath(FlatBufferBuilder builder, StringOffset filePathOffset) { builder.AddOffset(0, filePathOffset.Value, 0); }
        public static void AddFrameFingerPrints(FlatBufferBuilder builder, VectorOffset frameFingerPrintsOffset) { builder.AddOffset(1, frameFingerPrintsOffset.Value, 0); }
        public static VectorOffset CreateFrameFingerPrintsVector(FlatBufferBuilder builder, Offset<FrameFingerPrint>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static void StartFrameFingerPrintsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<VideoFingerPrint> EndVideoFingerPrint(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<VideoFingerPrint>(o);
        }
    };


}
