// automatically generated by the FlatBuffers compiler, do not modify

namespace Core
{

    using System;
    using FlatBuffers;

    internal struct VideoFingerPrintDatabaseMetaTable : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static VideoFingerPrintDatabaseMetaTable GetRootAsVideoFingerPrintDatabaseMetaTable(ByteBuffer _bb) { return GetRootAsVideoFingerPrintDatabaseMetaTable(_bb, new VideoFingerPrintDatabaseMetaTable()); }
        public static VideoFingerPrintDatabaseMetaTable GetRootAsVideoFingerPrintDatabaseMetaTable(ByteBuffer _bb, VideoFingerPrintDatabaseMetaTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public VideoFingerPrintDatabaseMetaTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public VideoFingerPrintDatabaseMetaTableEntry? DatabaseMetaTableEntries(int j) { int o = __p.__offset(4); return o != 0 ? (VideoFingerPrintDatabaseMetaTableEntry?)(new VideoFingerPrintDatabaseMetaTableEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int DatabaseMetaTableEntriesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

        public static Offset<VideoFingerPrintDatabaseMetaTable> CreateVideoFingerPrintDatabaseMetaTable(FlatBufferBuilder builder,
            VectorOffset databaseMetaTableEntriesOffset = default(VectorOffset))
        {
            builder.StartObject(1);
            VideoFingerPrintDatabaseMetaTable.AddDatabaseMetaTableEntries(builder, databaseMetaTableEntriesOffset);
            return VideoFingerPrintDatabaseMetaTable.EndVideoFingerPrintDatabaseMetaTable(builder);
        }

        public static void StartVideoFingerPrintDatabaseMetaTable(FlatBufferBuilder builder) { builder.StartObject(1); }
        public static void AddDatabaseMetaTableEntries(FlatBufferBuilder builder, VectorOffset databaseMetaTableEntriesOffset) { builder.AddOffset(0, databaseMetaTableEntriesOffset.Value, 0); }
        public static VectorOffset CreateDatabaseMetaTableEntriesVector(FlatBufferBuilder builder, Offset<VideoFingerPrintDatabaseMetaTableEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static void StartDatabaseMetaTableEntriesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<VideoFingerPrintDatabaseMetaTable> EndVideoFingerPrintDatabaseMetaTable(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<VideoFingerPrintDatabaseMetaTable>(o);
        }
        public static void FinishVideoFingerPrintDatabaseMetaTableBuffer(FlatBufferBuilder builder, Offset<VideoFingerPrintDatabaseMetaTable> offset) { builder.Finish(offset.Value); }
    };


}
