// automatically generated by the FlatBuffers compiler, do not modify

namespace Core
{

    using System;
    using FlatBuffers;

    internal struct VideoFingerPrintDatabaseMetaTableEntry : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static VideoFingerPrintDatabaseMetaTableEntry GetRootAsVideoFingerPrintDatabaseMetaTableEntry(ByteBuffer _bb) { return GetRootAsVideoFingerPrintDatabaseMetaTableEntry(_bb, new VideoFingerPrintDatabaseMetaTableEntry()); }
        public static VideoFingerPrintDatabaseMetaTableEntry GetRootAsVideoFingerPrintDatabaseMetaTableEntry(ByteBuffer _bb, VideoFingerPrintDatabaseMetaTableEntry obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public VideoFingerPrintDatabaseMetaTableEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string FileName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
        public ArraySegment<byte>? GetFileNameBytes() { return __p.__vector_as_arraysegment(4); }
        public ulong FileSize { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

        public static Offset<VideoFingerPrintDatabaseMetaTableEntry> CreateVideoFingerPrintDatabaseMetaTableEntry(FlatBufferBuilder builder,
            StringOffset fileNameOffset = default(StringOffset),
            ulong fileSize = 0)
        {
            builder.StartObject(2);
            VideoFingerPrintDatabaseMetaTableEntry.AddFileSize(builder, fileSize);
            VideoFingerPrintDatabaseMetaTableEntry.AddFileName(builder, fileNameOffset);
            return VideoFingerPrintDatabaseMetaTableEntry.EndVideoFingerPrintDatabaseMetaTableEntry(builder);
        }

        public static void StartVideoFingerPrintDatabaseMetaTableEntry(FlatBufferBuilder builder) { builder.StartObject(2); }
        public static void AddFileName(FlatBufferBuilder builder, StringOffset fileNameOffset) { builder.AddOffset(0, fileNameOffset.Value, 0); }
        public static void AddFileSize(FlatBufferBuilder builder, ulong fileSize) { builder.AddUlong(1, fileSize, 0); }
        public static Offset<VideoFingerPrintDatabaseMetaTableEntry> EndVideoFingerPrintDatabaseMetaTableEntry(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<VideoFingerPrintDatabaseMetaTableEntry>(o);
        }
    };


}
