// automatically generated by the FlatBuffers compiler, do not modify

namespace Core
{

    using System;
    using FlatBuffers;

    internal sealed class VideoFingerPrintDatabase : Table
    {
        public static VideoFingerPrintDatabase GetRootAsVideoFingerPrintDatabase(ByteBuffer _bb) { return GetRootAsVideoFingerPrintDatabase(_bb, new VideoFingerPrintDatabase()); }
        public static VideoFingerPrintDatabase GetRootAsVideoFingerPrintDatabase(ByteBuffer _bb, VideoFingerPrintDatabase obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public VideoFingerPrintDatabase __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

        public VideoFingerPrint GetVideoFingerPrints(int j) { return GetVideoFingerPrints(new VideoFingerPrint(), j); }
        public VideoFingerPrint GetVideoFingerPrints(VideoFingerPrint obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
        public int VideoFingerPrintsLength { get { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; } }

        public static Offset<VideoFingerPrintDatabase> CreateVideoFingerPrintDatabase(FlatBufferBuilder builder,
            VectorOffset videoFingerPrintsOffset = default(VectorOffset))
        {
            builder.StartObject(1);
            VideoFingerPrintDatabase.AddVideoFingerPrints(builder, videoFingerPrintsOffset);
            return VideoFingerPrintDatabase.EndVideoFingerPrintDatabase(builder);
        }

        public static void StartVideoFingerPrintDatabase(FlatBufferBuilder builder) { builder.StartObject(1); }
        public static void AddVideoFingerPrints(FlatBufferBuilder builder, VectorOffset videoFingerPrintsOffset) { builder.AddOffset(0, videoFingerPrintsOffset.Value, 0); }
        public static VectorOffset CreateVideoFingerPrintsVector(FlatBufferBuilder builder, Offset<VideoFingerPrint>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static void StartVideoFingerPrintsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<VideoFingerPrintDatabase> EndVideoFingerPrintDatabase(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<VideoFingerPrintDatabase>(o);
        }
        public static void FinishVideoFingerPrintDatabaseBuffer(FlatBufferBuilder builder, Offset<VideoFingerPrintDatabase> offset) { builder.Finish(offset.Value); }
    };


}
