// automatically generated by the FlatBuffers compiler, do not modify

namespace Core
{

    using System;
    using FlatBuffers;

    internal sealed class VideoFingerPrintDatabaseMetaTableEntry : Table
    {
        public static VideoFingerPrintDatabaseMetaTableEntry GetRootAsVideoFingerPrintDatabaseMetaTableEntry(ByteBuffer _bb) { return GetRootAsVideoFingerPrintDatabaseMetaTableEntry(_bb, new VideoFingerPrintDatabaseMetaTableEntry()); }
        public static VideoFingerPrintDatabaseMetaTableEntry GetRootAsVideoFingerPrintDatabaseMetaTableEntry(ByteBuffer _bb, VideoFingerPrintDatabaseMetaTableEntry obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public VideoFingerPrintDatabaseMetaTableEntry __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

        public string FileName { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
        public ArraySegment<byte>? GetFileNameBytes() { return __vector_as_arraysegment(4); }
        public ulong FileSize { get { int o = __offset(6); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }

        public static Offset<VideoFingerPrintDatabaseMetaTableEntry> CreateVideoFingerPrintDatabaseMetaTableEntry(FlatBufferBuilder builder,
            StringOffset fileNameOffset = default(StringOffset),
            ulong fileSize = 0)
        {
            builder.StartObject(2);
            VideoFingerPrintDatabaseMetaTableEntry.AddFileSize(builder, fileSize);
            VideoFingerPrintDatabaseMetaTableEntry.AddFileName(builder, fileNameOffset);
            return VideoFingerPrintDatabaseMetaTableEntry.EndVideoFingerPrintDatabaseMetaTableEntry(builder);
        }

        public static void StartVideoFingerPrintDatabaseMetaTableEntry(FlatBufferBuilder builder) { builder.StartObject(2); }
        public static void AddFileName(FlatBufferBuilder builder, StringOffset fileNameOffset) { builder.AddOffset(0, fileNameOffset.Value, 0); }
        public static void AddFileSize(FlatBufferBuilder builder, ulong fileSize) { builder.AddUlong(1, fileSize, 0); }
        public static Offset<VideoFingerPrintDatabaseMetaTableEntry> EndVideoFingerPrintDatabaseMetaTableEntry(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<VideoFingerPrintDatabaseMetaTableEntry>(o);
        }
    };


}
