// automatically generated by the FlatBuffers compiler, do not modify

namespace VideoIndexer
{
    using FlatBuffers;

    internal sealed class FrameFingerPrint : Table
    {
        public static FrameFingerPrint GetRootAsFrameFingerPrint(ByteBuffer _bb) { return GetRootAsFrameFingerPrint(_bb, new FrameFingerPrint()); }
        public static FrameFingerPrint GetRootAsFrameFingerPrint(ByteBuffer _bb, FrameFingerPrint obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public FrameFingerPrint __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

        public int FrameNumber { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
        public ulong PHash { get { int o = __offset(6); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }

        public static Offset<FrameFingerPrint> CreateFrameFingerPrint(FlatBufferBuilder builder,
            int frameNumber = 0,
            ulong pHash = 0)
        {
            builder.StartObject(2);
            FrameFingerPrint.AddPHash(builder, pHash);
            FrameFingerPrint.AddFrameNumber(builder, frameNumber);
            return FrameFingerPrint.EndFrameFingerPrint(builder);
        }

        public static void StartFrameFingerPrint(FlatBufferBuilder builder) { builder.StartObject(2); }
        public static void AddFrameNumber(FlatBufferBuilder builder, int frameNumber) { builder.AddInt(0, frameNumber, 0); }
        public static void AddPHash(FlatBufferBuilder builder, ulong pHash) { builder.AddUlong(1, pHash, 0); }
        public static Offset<FrameFingerPrint> EndFrameFingerPrint(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<FrameFingerPrint>(o);
        }
    };


}
